### ISSUE TITLE
NameError: name 'MeshDS' is not defined

### ISSUE THREAD

**Issue by JohnG0024** [amirhertz/maps#2]
Hi, I'm getting multiple errors when running `demo.py `
```
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from core import conformal_manger
  File "C:\Users\junew\Desktop\maps-main\maps-main\core\conformal_manger.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```
```
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from core import conformal_manger
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\conformal_manger.py", line 4, in <module>
    from core.decimate import Decimate
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\decimate.py", line 5, in <module>
    from core.mesh_ds import MeshDS
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\mesh_ds.py", line 25, in <module>
    class MeshDS(GeometryDS):
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\mesh_ds.py", line 184, in MeshDS
    def to(self, device: D) -> MeshDS:
NameError: name 'MeshDS' is not defined
```

**Comment by amirhertz** [comment]
See similar issue [here](https://github.com/csuhan/ReDet/issues/14).

A simple fix is to use python>=3.7

**Comment by JohnG0024** [comment]
@amirhertz 
Thanks, that fixed the problem. 

Is there any requirement for the input mesh? I'm getting an AssertionError when using the [stanford bunny](https://drive.google.com/file/d/1OHgvXasj6xmErz4tRFxbHvJUmkZp68_e/view?usp=share_link) with 69451 tris.

```
Traceback (most recent call last):
  File "demo.py", line 24, in <module>
    main()
  File "demo.py", line 12, in main
    cm = conformal_manger.ConformalManger(mesh, min_vs=num_faces // 32 + 2) 
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\conformal_manger.py", line 430, in __init__
    self.ds: Decimate = Decimate(raw_mesh, min_vs=min_vs)
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\decimate.py", line 395, in __init__
    self.queue, self.updated_positions = self.extract_independent_set()
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\decimate.py", line 331, in extract_independent_set
    return self.extract_low_independent_set()
  File "C:\Users\jg\Desktop\maps-main\maps-main\core\decimate.py", line 321, in extract_low_independent_set
    assert (edge_a - edge_d).eq(0).all().item()
AssertionError
```

**Comment by amirhertz** [comment]
The code works only with closed non-manifold triangular meshes. Maybe this is the issue.
